# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.function_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.function_tabs.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.function_tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.function_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.function_tabs.setObjectName("function_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.query_prompt = QtWidgets.QLabel(self.tab)
        self.query_prompt.setGeometry(QtCore.QRect(20, 40, 291, 16))
        self.query_prompt.setObjectName("query_prompt")
        self.query_button = QtWidgets.QPushButton(self.tab)
        self.query_button.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.query_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.query_button.setObjectName("query_button")
        self.query_input = QtWidgets.QLineEdit(self.tab)
        self.query_input.setGeometry(QtCore.QRect(20, 70, 701, 20))
        self.query_input.setObjectName("query_input")
        self.query_table = QtWidgets.QTableWidget(self.tab)
        self.query_table.setGeometry(QtCore.QRect(20, 230, 701, 291))
        self.query_table.setMinimumSize(QtCore.QSize(651, 192))
        self.query_table.setObjectName("query_table")
        self.query_table.setColumnCount(11)
        self.query_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.query_table.setHorizontalHeaderItem(10, item)
        self.function_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 600, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.check_initial = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_initial.setObjectName("check_initial")
        self.gridLayout.addWidget(self.check_initial, 0, 1, 1, 1)
        self.check_final = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_final.setObjectName("check_final")
        self.gridLayout.addWidget(self.check_final, 0, 2, 1, 1)
        self.check_tone = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_tone.setObjectName("check_tone")
        self.gridLayout.addWidget(self.check_tone, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.check_radical = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_radical.setObjectName("check_radical")
        self.gridLayout.addWidget(self.check_radical, 1, 1, 1, 1)
        self.check_structure = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_structure.setObjectName("check_structure")
        self.gridLayout.addWidget(self.check_structure, 1, 2, 1, 1)
        self.check_liushu = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_liushu.setObjectName("check_liushu")
        self.gridLayout.addWidget(self.check_liushu, 1, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.stroke_diff = QtWidgets.QSpinBox(self.layoutWidget)
        self.stroke_diff.setMinimum(-1)
        self.stroke_diff.setMaximum(10)
        self.stroke_diff.setProperty("value", -1)
        self.stroke_diff.setObjectName("stroke_diff")
        self.gridLayout.addWidget(self.stroke_diff, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.freq_diff = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.freq_diff.setDecimals(1)
        self.freq_diff.setMinimum(-1.0)
        self.freq_diff.setSingleStep(1.0)
        self.freq_diff.setProperty("value", -1.0)
        self.freq_diff.setObjectName("freq_diff")
        self.gridLayout.addWidget(self.freq_diff, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.match_table = QtWidgets.QTableWidget(self.tab_2)
        self.match_table.setGeometry(QtCore.QRect(30, 230, 701, 291))
        self.match_table.setMinimumSize(QtCore.QSize(651, 192))
        self.match_table.setObjectName("match_table")
        self.match_table.setColumnCount(11)
        self.match_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(10, item)
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(32, 171, 691, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.match_prompt = QtWidgets.QLabel(self.widget)
        self.match_prompt.setMaximumSize(QtCore.QSize(159, 16777215))
        self.match_prompt.setObjectName("match_prompt")
        self.horizontalLayout.addWidget(self.match_prompt)
        self.match_input = QtWidgets.QLineEdit(self.widget)
        self.match_input.setMaxLength(1)
        self.match_input.setObjectName("match_input")
        self.horizontalLayout.addWidget(self.match_input)
        self.match_button = QtWidgets.QPushButton(self.widget)
        self.match_button.setObjectName("match_button")
        self.horizontalLayout.addWidget(self.match_button)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.status = QtWidgets.QLineEdit(self.widget)
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        self.function_tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.generate_table = QtWidgets.QTableWidget(self.tab_3)
        self.generate_table.setGeometry(QtCore.QRect(20, 160, 721, 371))
        self.generate_table.setMinimumSize(QtCore.QSize(651, 192))
        self.generate_table.setObjectName("generate_table")
        self.generate_table.setColumnCount(11)
        self.generate_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.generate_table.setHorizontalHeaderItem(10, item)
        self.widget1 = QtWidgets.QWidget(self.tab_3)
        self.widget1.setGeometry(QtCore.QRect(20, 30, 680, 98))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(self.widget1)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.big_freq = QtWidgets.QDoubleSpinBox(self.widget1)
        self.big_freq.setDecimals(1)
        self.big_freq.setMaximum(10.0)
        self.big_freq.setProperty("value", 10.0)
        self.big_freq.setObjectName("big_freq")
        self.gridLayout_2.addWidget(self.big_freq, 2, 8, 1, 1)
        self.big_stroke = QtWidgets.QSpinBox(self.widget1)
        self.big_stroke.setMaximum(30)
        self.big_stroke.setProperty("value", 30)
        self.big_stroke.setObjectName("big_stroke")
        self.gridLayout_2.addWidget(self.big_stroke, 2, 5, 1, 1)
        self.generate_button = QtWidgets.QPushButton(self.widget1)
        self.generate_button.setObjectName("generate_button")
        self.gridLayout_2.addWidget(self.generate_button, 2, 9, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.tone_box = QtWidgets.QLineEdit(self.widget1)
        self.tone_box.setObjectName("tone_box")
        self.gridLayout_2.addWidget(self.tone_box, 0, 9, 1, 1)
        self.init_box = QtWidgets.QLineEdit(self.widget1)
        self.init_box.setObjectName("init_box")
        self.gridLayout_2.addWidget(self.init_box, 0, 2, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 5, 1, 1)
        self.final_box = QtWidgets.QLineEdit(self.widget1)
        self.final_box.setObjectName("final_box")
        self.gridLayout_2.addWidget(self.final_box, 0, 6, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget1)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.small_freq = QtWidgets.QDoubleSpinBox(self.widget1)
        self.small_freq.setDecimals(1)
        self.small_freq.setObjectName("small_freq")
        self.gridLayout_2.addWidget(self.small_freq, 2, 7, 1, 1)
        self.small_stroke = QtWidgets.QSpinBox(self.widget1)
        self.small_stroke.setObjectName("small_stroke")
        self.gridLayout_2.addWidget(self.small_stroke, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 1, 1, 3)
        self.liushu_combo = QtWidgets.QComboBox(self.widget1)
        self.liushu_combo.setObjectName("liushu_combo")
        self.gridLayout_2.addWidget(self.liushu_combo, 1, 9, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget1)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 8, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget1)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 1, 1, 1)
        self.radical_combo = QtWidgets.QComboBox(self.widget1)
        self.radical_combo.setObjectName("radical_combo")
        self.gridLayout_2.addWidget(self.radical_combo, 1, 2, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 5, 1, 1)
        self.structure_combo = QtWidgets.QComboBox(self.widget1)
        self.structure_combo.setObjectName("structure_combo")
        self.gridLayout_2.addWidget(self.structure_combo, 1, 6, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.function_tabs.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.function_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.query_prompt.setText(_translate("MainWindow", "Enter the character(s)"))
        self.query_button.setText(_translate("MainWindow", "Query"))
        item = self.query_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Character"))
        item = self.query_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unicode"))
        item = self.query_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial"))
        item = self.query_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Final"))
        item = self.query_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tone"))
        item = self.query_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Pinyin"))
        item = self.query_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Structure"))
        item = self.query_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Liushu"))
        item = self.query_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Radical"))
        item = self.query_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Strokes"))
        item = self.query_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Frequency"))
        self.function_tabs.setTabText(self.function_tabs.indexOf(self.tab), _translate("MainWindow", "Query"))
        self.label_6.setText(_translate("MainWindow", "Select feature(s) for matching"))
        self.label.setText(_translate("MainWindow", "Phonological features"))
        self.check_initial.setText(_translate("MainWindow", "Initial"))
        self.check_final.setText(_translate("MainWindow", "Final"))
        self.check_tone.setText(_translate("MainWindow", "Tone"))
        self.label_2.setText(_translate("MainWindow", "Orthographic features"))
        self.check_radical.setText(_translate("MainWindow", "Radical"))
        self.check_structure.setText(_translate("MainWindow", "Structure"))
        self.check_liushu.setText(_translate("MainWindow", "Liushu Classification"))
        self.label_3.setText(_translate("MainWindow", "Statistical features"))
        self.label_4.setText(_translate("MainWindow", "Difference of stroke numbers"))
        self.label_5.setText(_translate("MainWindow", "Difference of logged frequency"))
        item = self.match_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Character"))
        item = self.match_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unicode"))
        item = self.match_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial"))
        item = self.match_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Final"))
        item = self.match_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tone"))
        item = self.match_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Pinyin"))
        item = self.match_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Structure"))
        item = self.match_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Liushu"))
        item = self.match_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Radical"))
        item = self.match_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Strokes"))
        item = self.match_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Frequency"))
        self.match_prompt.setText(_translate("MainWindow", "Enter one character for matching"))
        self.match_button.setText(_translate("MainWindow", "Match"))
        self.label_10.setText(_translate("MainWindow", "Status:"))
        self.function_tabs.setTabText(self.function_tabs.indexOf(self.tab_2), _translate("MainWindow", "Match"))
        item = self.generate_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Character"))
        item = self.generate_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unicode"))
        item = self.generate_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial"))
        item = self.generate_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Final"))
        item = self.generate_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tone"))
        item = self.generate_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Pinyin"))
        item = self.generate_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Structure"))
        item = self.generate_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Liushu"))
        item = self.generate_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Radical"))
        item = self.generate_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Strokes"))
        item = self.generate_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Frequency"))
        self.label_19.setText(_translate("MainWindow", "Select features for character generation"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
        self.label_8.setText(_translate("MainWindow", "Phonological features"))
        self.label_13.setText(_translate("MainWindow", "Final"))
        self.label_12.setText(_translate("MainWindow", "Tone"))
        self.label_17.setText(_translate("MainWindow", "Frequency range"))
        self.label_9.setText(_translate("MainWindow", "Statistical features"))
        self.label_11.setText(_translate("MainWindow", "Initial"))
        self.label_7.setText(_translate("MainWindow", "Orthographic features"))
        self.label_16.setText(_translate("MainWindow", "Strokes range"))
        self.label_15.setText(_translate("MainWindow", "Liushu"))
        self.label_18.setText(_translate("MainWindow", "Radical"))
        self.label_14.setText(_translate("MainWindow", "Structure"))
        self.function_tabs.setTabText(self.function_tabs.indexOf(self.tab_3), _translate("MainWindow", "Generate"))

